import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import "@/app/globals.css";
import { AdminDrawer } from "@/components/admin/Drawer"
import React from 'react'
import { NotificationProvider } from "@/context/NotificationContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <NotificationProvider>
    <div >
      
      {/* Drawer يظهر في كل صفحات admin */}
      <AdminDrawer  />

      <main className="p-4">
        {children}
      </main>
      
    </div>
    </NotificationProvider>
  );
}
